<?xml version="1.0"?>
<package format="3">
  <name>track_robot_bringup</name>
  <version>0.0.1</version>
  <description>Launch files and parameters for Track Robot bringup.</description>

  <maintainer email="TODO@TODO.com">TODO</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <!-- launch 运行时依赖 -->
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <!-- 后面一般还会用到 -->
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>nav2_rviz_plugins</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>python3-opencv</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>track_robot_interfaces</exec_depend>
  <exec_depend>track_robot_perception</exec_depend>
  <exec_depend>track_robot_sensor_bringup</exec_depend>
  <exec_depend>track_robot_semantic_search</exec_depend>
  <exec_depend>track_robot_lidar_tracking</exec_depend>
  <exec_depend>track_robot_semantic_memory</exec_depend>
  <exec_depend>track_robot_semantic_search_rviz_plugins</exec_depend>
  <exec_depend>bunker_base</exec_depend>
  <exec_depend>bunker_pro2</exec_depend>
  <exec_depend>zed_wrapper</exec_depend>
  <exec_depend>track_robot_core</exec_depend>
  <exec_depend>track_robot_control</exec_depend>
  <exec_depend>track_robot_decision</exec_depend>
  <exec_depend>track_robot_safety</exec_depend>
  <exec_depend>track_robot_navigation</exec_depend>

  <test_depend>ament_cmake_pytest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
