<?xml version="1.0"?>
<package format="3">
  <name>track_robot_teleop</name>
  <version>0.0.0</version>
  <description>Teleoperation nodes for track robot</description>
  <maintainer email="track-robot@todo.todo">track-robot</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>track_robot_interfaces</depend>

  <exec_depend>python3-pynput</exec_depend>
  <exec_depend>python3-pyqt5</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
