keyboard_teleop_node:
  ros__parameters:
    publish_rate: 20.0
    cmd_vel_topic: "/teleop/cmd_vel"

    max_linear_speed: 0.6
    max_angular_speed: 1.0

    linear_acc_step: 0.4
    angular_acc_step: 0.8

    zero_on_release: true
