<?xml version="1.0"?>
<package format="3">
  <name>track_robot_control</name>
  <version>0.0.1</version>
  <description>Control and high-level logic for Track Robot.</description>

  <maintainer email="TODO@TODO.com">TODO</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- 先把常用依赖写上，后面写 node 一般都会用 -->
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>

  <!-- 未来如果要用你自己的 msg/srv，就启用 -->
  <depend>track_robot_interfaces</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
